export const BLOCK_LOAD_REQUEST = 'BLOCK_LOAD_REQUEST';
export const BLOCK_LOAD_SUCCESS = 'BLOCK_LOAD_SUCCESS';
export const BLOCK_LOAD_FAIL = 'BLOCK_LOAD_FAIL';

export const BLOCKS_LOAD_REQUEST = 'BLOCKS_LOAD_REQUEST';
export const BLOCKS_LOAD_SUCCESS = 'BLOCKS_LOAD_SUCCESS';
export const BLOCKS_LOAD_FAIL = 'BLOCKS_LOAD_FAIL';

export const BLOCK_ADD_REQUEST = 'BLOCK_ADD_REQUEST';
export const BLOCK_ADD_SUCCESS = 'BLOCK_ADD_SUCCESS';
export const BLOCK_ADD_FAIL = 'BLOCK_ADD_FAIL';

export const BLOCK_UPDATE_REQUEST = 'BLOCK_UPDATE_REQUEST';
export const BLOCK_UPDATE_SUCCESS = 'BLOCK_UPDATE_SUCCESS';
export const BLOCK_UPDATE_FAIL = 'BLOCK_UPDATE_FAIL';

export const BLOCK_DELETE_REQUEST = 'BLOCK_DELETE_REQUEST';
export const BLOCK_DELETE_SUCCESS = 'BLOCK_DELETE_SUCCESS';
export const BLOCK_DELETE_FAIL = 'BLOCK_DELETE_FAIL';
