export const COLLECTION_LOAD_REQUEST = 'COLLECTION_LOAD_REQUEST';
export const COLLECTION_LOAD_SUCCESS = 'COLLECTION_LOAD_SUCCESS';
export const COLLECTION_LOAD_FAIL = 'COLLECTION_LOAD_FAIL';

export const COLLECTIONS_LOAD_REQUEST = 'COLLECTIONS_LOAD_REQUEST';
export const COLLECTIONS_LOAD_SUCCESS = 'COLLECTIONS_LOAD_SUCCESS';
export const COLLECTIONS_LOAD_FAIL = 'COLLECTIONS_LOAD_FAIL';

export const COLLECTION_ADD_REQUEST = 'COLLECTION_ADD_REQUEST';
export const COLLECTION_ADD_SUCCESS = 'COLLECTION_ADD_SUCCESS';
export const COLLECTION_ADD_FAIL = 'COLLECTION_ADD_FAIL';

export const COLLECTION_UPDATE_REQUEST = 'COLLECTION_UPDATE_REQUEST';
export const COLLECTION_UPDATE_SUCCESS = 'COLLECTION_UPDATE_SUCCESS';
export const COLLECTION_UPDATE_FAIL = 'COLLECTION_UPDATE_FAIL';

export const COLLECTION_DELETE_REQUEST = 'COLLECTION_DELETE_REQUEST';
export const COLLECTION_DELETE_SUCCESS = 'COLLECTION_DELETE_SUCCESS';
export const COLLECTION_DELETE_FAIL = 'COLLECTION_DELETE_FAIL';
