export const WORKPLACE_LOAD_REQUEST = 'WORKPLACE_LOAD_REQUEST';
export const WORKPLACE_LOAD_SUCCESS = 'WORKPLACE_LOAD_SUCCESS';
export const WORKPLACE_LOAD_FAIL = 'WORKPLACE_LOAD_FAIL';

export const WORKPLACES_LOAD_REQUEST = 'WORKPLACES_LOAD_REQUEST';
export const WORKPLACES_LOAD_SUCCESS = 'WORKPLACES_LOAD_SUCCESS';
export const WORKPLACES_LOAD_FAIL = 'WORKPLACES_LOAD_FAIL';

export const WORKPLACE_ADD_REQUEST = 'WORKPLACE_ADD_REQUEST';
export const WORKPLACE_ADD_SUCCESS = 'WORKPLACE_ADD_SUCCESS';
export const WORKPLACE_ADD_FAIL = 'WORKPLACE_ADD_FAIL';

export const WORKPLACE_UPDATE_REQUEST = 'WORKPLACE_UPDATE_REQUEST';
export const WORKPLACE_UPDATE_SUCCESS = 'WORKPLACE_UPDATE_SUCCESS';
export const WORKPLACE_UPDATE_FAIL = 'WORKPLACE_UPDATE_FAIL';

export const WORKPLACE_DELETE_REQUEST = 'WORKPLACE_DELETE_REQUEST';
export const WORKPLACE_DELETE_SUCCESS = 'WORKPLACE_DELETE_SUCCESS';
export const WORKPLACE_DELETE_FAIL = 'WORKPLACE_DELETE_FAIL';

